### ISSUE TITLE
Workshop_01: Typos and inconsistencies

### ISSUE THREAD

**Issue by haotrn** [IS3UniCologne/AA_2024#1]
Inside of the Jupyter notebook of the first workshop (`AA_WS_01_Setup_pre.ipynb`), there are a few typos and errors in the text, as well as some inconsistencies between the description and the code for some examples.

**Comment by haotrn** [comment]
Please see the following '.json' for a suggestion:

[AA_WS_01_Setup_pre.json](https://github.com/user-attachments/files/17594148/AA_WS_01_Setup_pre.json)

**Comment by janikmu** [comment]
Thanks for bringing this up. Please create a pull request, which I can then review and depending on the contents, merge.

**Comment by haotrn** [comment]
Sure, see the pull request https://github.com/IS3UniCologne/AA_2024/pull/2
